### ISSUE TITLE
Find out and notify when a user is disconnected and automatically allow rejoin with that name to the previous team

### ISSUE THREAD

**Issue by JustMyGithub** [upb-flunkyteam/flunkysimulator#59]

**Comment by stheid** [comment]
any practical ideas how to achieve that with the current protocol?

**Comment by JustMyGithub** [comment]
Maybe Websockets? I did not look at the protocol.

**Comment by ApolloLV** [comment]
@moreApi told me that he should be able to refactor the backend so that we can keep track of which streams associated with which players are still working. 
This info would then be added to the game state object for the javascript client to display, making it possible to spot a disconnected player. This info can also be utilised on the server side to disallow connecting with a user name that has an active stream ("Thomas' attack"), while allowing a client that experiences connection issues or reloads the page to reclaim the user.

**Comment by moreApi** [comment]
solved by ##112
