### ISSUE TITLE
Improved username escaping

### ISSUE THREAD

**Issue by stheid** [upb-flunkyteam/flunkysimulator#93]
The server should not escape umlauts or similar, because this is not needed for XSS safety, however is really ugly in the chat

**Comment by moreApi** [comment]
Currently the server uses org.apache.commons.text.StringEscapeUtils.escapeHtml4. Im not sure how to irgnore umlatus in there.

**Comment by ApolloLV** [comment]
"An alternative to Apache Commons: Use Spring's HtmlUtils.htmlEscape(String input) method." - "Thanks. I've used it (instead of StringEscapeUtils.escapeHtml() from apache-commons 2.6) because it leaves Russian characters as is." (from https://stackoverflow.com/questions/1265282/recommended-method-for-escaping-html-in-java)

**Comment by stheid** [comment]
It's definetly way better, but there is still a small thing wrong. The msg content is correct, but the playername is still strangely escaped

![image](https://user-images.githubusercontent.com/2736207/84509531-1f7bdc80-acc4-11ea-93d7-2321aa49fa23.png)
![image](https://user-images.githubusercontent.com/2736207/84509590-3a4e5100-acc4-11ea-9c40-563a1ae019da.png)

**Comment by moreApi** [comment]
The last issue should be fixed with #39. The textbox we currently use for chat display seems to intrepret the escaped symbols diffferently thaht the regular html elements.
